# LogThing Configuration File

[inputs.file]
path = "logs/"
log_kinds = ["INFO", "WARNING", "ERROR", "DEBUG", "TRACE", "FATAL"]

[processor]
level_pattern = "\\[(INFO|WARNING|ERROR|DEBUG|TRACE|FATAL)\\]"
timestamp_pattern = "(\\d{4}-\\d{2}-\\d{2}\\s+\\d{2}:\\d{2}:\\d{2})"
tag_pattern = "\\[([A-Z0-9_]+)\\]"

[web]
port = 9_595

# TODO: implement alerts
[alerts.error_spike]
condition = "when $error_rate > 100 per min"
window = "5m"
# TODO: setup email
# notify = ["email:ops@example.com"]
