# * LogThing Configuration File
#
# If you delete/comment out a key, LogThing will not use it
# e.g Comment out `timestamp_pattern` and LogThing will not look for timestamps

[inputs.file]
# directory containing logs
path = "logs/"

# log levels
log_kinds = ["INFO", "WARNING", "ERROR", "DEBUG", "TRACE", "FATAL"]

[processor]
# regex to extract level
level_pattern = "\\[(INFO|WARNING|ERROR|DEBUG|TRACE|FATAL)\\]"

# regex to extract timestamp
timestamp_pattern = "(\\d{4}-\\d{2}-\\d{2}\\_\\d{2}:\\d{2}:\\d{2})"

# regex to extract tag (e.g. thread name)
tag_pattern = "\\[([A-Z0-9_]+)\\]"

[web]
# port to serve dashboard on
port = 9_595

# TODO: implement alerts
[alerts.error_spike]
# rule to send alert when there are more than 100 errors per minute
condition = "when $error_rate > 100 per min"

# the window to check condition
window = "5m"

# TODO: setup email
## email to send alert to
#notify = ["email:ops@example.com"]
