# this is an example config file

[inputs.file]
path = "logs/"
log_kinds = ["INFO", "WARNING", "ERROR", "DEBUG", "TRACE", "FATAL"]

[processor]
level_pattern = "INFO|WARNING|ERROR|DEBUG|TRACE|FATAL"

# TODO: implement alerts
#[alerts.error_spike]
#condition = "error_rate > 100/min"
#window = "5m"
#notify = ["email:ops@example.com"]
